export const HERO_IMAGE = "https://media.base44.com/images/public/6a65d0914e87aef9bfc9268b/30f56b3f9_generated_image.png";

export const PORTAL_URL = "https://www.lab.sma1wonosari.sch.id/home";

export const LABS = [
  {
    id: "lab-kimia",
    name: "Lab Kimia",
    tag: "CHEM-01",
    discipline: "Chemistry",
    image: "https://media.base44.com/images/public/6a65d0914e87aef9bfc9268b/a3202d63f_generated_image.png",
    description: "Pusat eksplorasi reaksi kimia, titrasi, dan analisis bahan. Dilengkapi peralatan kaca presisi dan sistem ventilasi laboratorium standar.",
    equipment: ["Set Alat Distilasi", "Neraca Analitik", "Gelas Ukur Bersertifikat", "Lemari Asam", "Hot Plate Magnetic"],
    head: "Dra. Siti Rahmawati, M.Si",
    status: "available",
    span: "lg:col-span-5",
    capacity: "32 Peserta Didik",
    schedule: "Senin — Rabu, 08:00 — 14:30",
    rules: [
      "Wajib mengenakan jas laboratorium dan kaca mata pelindung",
      "Dilarang membuka botol reagen tanpa instruksi guru",
      "Semua limbah harus dibuang ke tempat yang telah disediakan",
      "Lapor segera jika terjadi tumpahan atau kebocoran",
    ],
    highlights: [
      "Sertifikasi K-201 Laboratorium Kimia",
      "Tersedia 16 set peralatan praktikum",
      "Sistem ventilasi aktif standar laboratorium",
    ],
  },
  {
    id: "lab-biologi",
    name: "Lab Biologi",
    tag: "BIO-02",
    discipline: "Biology",
    image: "https://media.base44.com/images/public/6a65d0914e87aef9bfc9268b/121f34bf0_generated_image.png",
    description: "Ruang pengamatan mikroorganisme, anatomi, dan ekosistem. Menyediakan mikroskop canggih dan koleksi preparat lengkap.",
    equipment: ["Mikroskop Binokuler", "Set Preparat permanen", "Mikrotom", "Inkubator Bacteriological", "Kotak Insektarium"],
    head: "Drs. Bambang Wijaya, M.Pd",
    status: "in-session",
    span: "lg:col-span-7",
    capacity: "36 Peserta Didik",
    schedule: "Selasa — Kamis, 08:00 — 14:30",
    rules: [
      "Wajib mencuci tangan sebelum dan sesudah praktikum",
      "Dilarang memakan atau minum di dalam laboratorium",
      "Gunakan sarung tangan saat menangani spesimen",
      "Kembalikan mikroskop ke posisi semula setelah digunakan",
    ],
    highlights: [
      "Koleksi preparat permanen lebih dari 200 slide",
      "Mikroskop binokuler dengan kamera digital",
      "Tersedia area preparat dan inkubasi",
    ],
  },
  {
    id: "lab-fisika",
    name: "Lab Fisika",
    tag: "PHY-03",
    discipline: "Physics",
    image: "https://media.base44.com/images/public/6a65d0914e87aef9bfc9268b/485a40e87_generated_image.png",
    description: "Laboratorium mekanika, optik, dan kelistrikan. Tempat pembuktian hukum fisika melalui eksperimen terukur dan presisi tinggi.",
    equipment: ["Set Optik Lengkap", "Power Supply DC/AC", "Track Dinamika", "Osiloskop Dual Trace", "Sensor Pasco"],
    head: "Dr. Agus Prasetyo, M.Si",
    status: "available",
    span: "lg:col-span-7",
    capacity: "32 Peserta Didik",
    schedule: "Senin — Rabu, 10:00 — 16:00",
    rules: [
      "Periksa kondisi peralatan sebelum digunakan",
      "Dilarang memasukkan benda asing ke dalam peralatan optik",
      "Matikan semua peralatan elektronik setelah selesai",
      "Laporkan kerusakan peralatan kepada pengawas lab",
    ],
    highlights: [
      "Sensor digital Pasco untuk pengukuran presisi",
      "Set optik lengkap untuk eksperimen cahaya",
      "Osilloskop dual trace untuk analisis sinyal",
    ],
  },
  {
    id: "lab-virtual",
    name: "Lab Virtual",
    tag: "ICT-04",
    discipline: "Virtual / ICT",
    image: "https://media.base44.com/images/public/6a65d0914e87aef9bfc9268b/d7955e6f0_generated_image.png",
    description: "Pusat simulasi digital dan pembelajaran berbasis komputer. Menyediakan akses laboratorium virtual interaktif dan simulasi fenomena sains.",
    equipment: ["40 Unit PC All-in-One", "Software Simulasi PhET", "Proyektor 4K Interaktif", "Server Lokal", "Akses LabXchange"],
    head: "Rizki Ananda, S.Kom",
    status: "available",
    span: "lg:col-span-5",
    capacity: "40 Peserta Didik",
    schedule: "Senin — Jumat, 08:00 — 15:00",
    rules: [
      "Dilarang menginstal software tanpa izin",
      "Gunakan akun masing-masing untuk login",
      "Simpan hasil kerja di folder yang telah ditentukan",
      "Matikan PC dengan benar setelah selesai",
    ],
    highlights: [
      "40 unit PC All-in-One spek tinggi",
      "Akses simulasi PhET dan LabXchange",
      "Proyektor 4K interaktif untuk presentasi",
    ],
  },
];

export const RESOURCES = [
  {
    id: "katalog",
    title: "Katalog",
    desc: "Daftar lengkap inventaris alat dan bahan laboratorium IPA.",
    icon: "BookOpen",
    content: "Katalog inventaris laboratorium IPA MAN Palopo memuat daftar lengkap seluruh peralatan, bahan kimia, dan consumable yang tersedia di setiap laboratorium. Setiap item tercatat dengan kode inventaris, kondisi, lokasi penyimpanan, dan status ketersediaan.",
    items: [
      "Peralatan Kimia — 45 jenis alat",
      "Peralatan Biologi — 38 jenis alat",
      "Peralatan Fisika — 42 jenis alat",
      "Peralatan ICT — 40 unit PC + aksesoris",
      "Bahan Kimia — 120+ jenis reagen",
      "Consumable — 60+ jenis bahan habis pakai",
    ],
  },
  {
    id: "struktur",
    title: "Struktur Organisasi",
    desc: "Susunan kepengurusan dan tata kelola laboratorium.",
    icon: "Network",
    content: "Struktur organisasi laboratorium IPA MAN Palopo terdiri dari Kepala Laboratorium, Koordinator setiap bidang, dan tenaga teknis pendukung. Setiap posisi memiliki tanggung jawab dan wewenang yang terdefinisi dalam organisasi.",
    items: [
      "Kepala Laboratorium IPA",
      "Koordinator Lab Kimia & Biologi",
      "Koordinator Lab Fisika & Virtual",
      "Tenaga Teknis Laboratorium",
      "Administrasi & Pengadaan",
    ],
  },
  {
    id: "layanan",
    title: "Layanan Laboratorium",
    desc: "Jenis pelayanan dan jadwal pemanfaatan ruang lab.",
    icon: "ConciergeBell",
    content: "Laboratorium IPA MAN Palopo melayani kegiatan praktikum kurikulum, penelitian siswa, olimpiade sains, dan peminjaman fasilitas untuk kegiatan akademik. Jadwal pemanfaatan dapat diakses melalui portal informasi.",
    items: [
      "Praktikum Kurikulum — Senin s/d Jumat",
      "Penelitian Siswa — Jam Lab Tersedia",
      "Olimpiade Sains — Sesuai Jadwal",
      "Peminjaman Fasilitas — Ajukan via Portal",
      "Konsultasi Teknis — Hubungi Koordinator",
    ],
  },
  {
    id: "sop",
    title: "SOP Praktikum",
    desc: "Prosedur operasi baku pelaksanaan praktikum yang aman.",
    icon: "ClipboardCheck",
    content: "Standar Operasional Prosedur (SOP) praktikum laboratorium IPA dirancang untuk menjamin keselamatan dan keamanan seluruh peserta didik dan pendidik. SOP mencakup prosedur sebelum, selama, dan sesudah praktikum.",
    items: [
      "Prosedur Keselamatan Laboratorium",
      "Penggunaan APD (Alat Pelindung Diri)",
      "Penanganan Limbah Kimia & Biologi",
      "Prosedur Darurat & Evakuasi",
      "Pencatatan & Pelaporan Insiden",
    ],
  },
  {
    id: "lembar-kerja",
    title: "Lembar Kerja Praktikum",
    desc: "Modul dan lembar kerja siap pakai untuk kegiatan praktik.",
    icon: "FileText",
    content: "Lembar kerja praktikum laboratorium IPA MAN Palopo disusun mengacu pada kurikulum terkini dan disesuaikan dengan peralatan yang tersedia. Setiap modul memuat tujuan, alat & bahan, prosedur, dan panduan analisis data.",
    items: [
      "Modul Kimia — 12 Paket Praktikum",
      "Modul Biologi — 10 Paket Praktikum",
      "Modul Fisika — 11 Paket Praktikum",
      "Modul Virtual — 8 Simulasi Interaktif",
      "Lembar Evaluasi & Rubrik Penilaian",
    ],
  },
];

export const GALLERY = [
  { lab: "Lab Kimia", items: ["Pintu masuk Lab Kimia", "Ruang penyimpanan alat", "Ruang Praktikum", "Bak cuci", "Almari penyimpanan bahan", "Ruang Praktikum"] },
  { lab: "Lab Fisika", items: ["Pintu masuk Lab Fisika", "Ruang Praktikum", "Bak cuci", "Ruang Praktikum", "Ruang penyimpanan alat"] },
  { lab: "Lab Biologi", items: ["Pintu masuk Lab Biologi", "Tempat penyimpanan mikroskop", "Almari penyimpanan alat", "Almari tempat penyimpanan alat"] },
];

export const NAV_LINKS = [
  { label: "Beranda", href: "/" },
  { label: "Laboratorium", href: "/pusat-keunggulan" },
  { label: "Layanan", href: "/arsip-akademik" },
  { label: "Galeri", href: "/galeri-lab" },
  { label: "Tentang", href: "/#about" },
  { label: "Kontak", href: "/#contact" },
];
